services:
  oracle21c:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PDB: orcl 
      ORACLE_PWD: P@ssw0rd1!
    ports:
      - '1521:1521'
      - '5500:5500'
    volumes:
      - oracle21c-data:/opt/oracle/oradata
volumes:
  oracle21c-data: